# Generated by Django 4.2.2 on 2023-06-05 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habit_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('todays_value', models.IntegerField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Habit_Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_value', models.IntegerField(blank=True, null=True)),
                ('goal_value', models.IntegerField(blank=True, null=True)),
                ('goal_date', models.DateField()),
                ('post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(max_length=400)),
                ('title', models.CharField(max_length=30)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('habit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.genre')),
            ],
        ),
    ]
