# Generated by Django 4.2.2 on 2023-06-07 20:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_habit_goal_habit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='goal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.habit_goal'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tracker',
            name='check_in_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
