# Generated by Django 4.2.2 on 2023-06-08 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_tracker_goal_alter_tracker_check_in_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Trackers', to='tracker.habit_goal'),
        ),
    ]
