# Generated by Django 4.2.2 on 2023-06-09 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_alter_tracker_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='goal_value',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tracker.habit_goal'),
            preserve_default=False,
        ),
    ]
