# Generated by Django 4.2.2 on 2023-06-09 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_tracker_goal_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracker',
            name='goal_value',
        ),
    ]
